name: weather_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  provider: ^6.0.5
  get_it: ^7.6.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  responsive_sizer: ^3.2.0
  pretty_dio_logger: ^1.3.1
  flutter_spinkit: ^5.2.0
  animate_do: ^3.1.2
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  #  branding: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
  web: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic